<a href="https://colab.research.google.com/github/muhlis-id/Data-Science_240401010197_Muhlis/blob/main/Pertemuan02_Muhlis_240401010197.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pertemuan 2

Nama: MUHLIS
NIM: 240401010197
Kelas: IF405

In [ ]:
# LIST OPERATION

# Membuat List
data = [10, 20, 'Python', True, 3.14]

# Akses & Slicing
print(data[0])          # > 10
print(data[-1])         # > 3.14 (dari belakang)
print(data[1:3])        # > [20, 'Python']

#Manipulasi
data.append(99)         # Tambah di akhir
data.insert(1, 55)      # Sisipkan di posisi 1
data.remove(20)         # hapus nilai pertama = 20
#data.sort()             # urutkan (jika type sama)
data.sort(key=str)      # alternatif menggunakan string

10
3.14
[20, 'Python']


In [ ]:
# DICTIONARY OPERATION

mahasiswa = {
    'nama': 'Budi Santoso',
    'nim': '2024001',
    'prodi': 'Informatika',
    'ipk': '3.85'
}

#Akses Nilai
print(mahasiswa['nama'])
print(mahasiswa.get('usia', 0))     # default jika key tidak ada

#Update dan hapus
mahasiswa['angkatan'] = 2024        # tambah key angjatan
del mahasiswa['nim']                # hapus key

Budi Santoso
0


In [ ]:
# MEMBUAT NUMPY ARRAY
import numpy as np

# Dari list python
a1D = np.array([1, 2, 3, 4, 5])         # 1D
a2D = np.array([[1,2,3],[3,5,6]])       # 2D

# Array dari nilai inisial
zeros = np.zeros((3,4))                 # nol semua
ones = np.ones((2,3))                  # satu semua
eye = np.eye(4)                        # matriks identitas
full = np.full((2, 2), 7)               # nilai konstan

# Sequence
arange = np.arange(0, 20, 2)        # 0,2,4,...18
linsp = np.linspace(0, 1, 11)       # 11 titik merata

# Array acak (reproducible)
rng = np.random.default_rng(seed=42)
rand_int = rng.integers(0, 100, (3, 4))
rand_flt = rng.normal(loc=0, scale=1, size=(100,))

In [ ]:
# Operasi Vektorisasi & Fungsi Statistik

# Operasi aritmetika vektorisasi
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a + b) # → [11 22 33 44 55]
print(a * b) # → [10 40 90 160 250]
print(a ** 2) # → [1 4 9 16 25]
# Universal functions (ufuncs)
np.sqrt(a) # akar kuadrat tiap elemen
np.exp(a) # eksponensial (e^x)
np.log(b) # logaritma natural
# Fungsi statistik
data = rng.normal(0, 1, 1000)
print(f'Mean: {np.mean(data):.4f}')
print(f'Std: {np.std(data):.4f}')
print(f'Min: {np.min(data):.4f}')
print(f'Max: {np.max(data):.4f}')
print(f'Q1: {np.percentile(data,25):.4f}')
print(f'Q3: {np.percentile(data,75):.4f}')

[11 22 33 44 55]
[ 10  40  90 160 250]
[ 1  4  9 16 25]
Mean: -0.0163
Std: 1.0008
Min: -3.6484
Max: 3.1789
Q1: -0.6897
Q3: 0.6163


Kesimpulan
1. Dalam melakukan pengurutan (sort) list, perlu ditentukan type data yang sama. Jika tidak sama, sebagai alternatif disamakan menggunakan type string
2.